id: I3A33C90A
legacy_id: P010588
ocr_import_info:
  bdrc_scan_id: W1KG15408
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T01:52:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:19:41.592846+00:00'
last_modified: 2022-08-31 16:19:59.806070
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15408
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15408
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཧོར་ཆོས་འབྱུང་། ༼བཀྲ་ཤིས་ཆོས་འབྱོར་གླིང་གི་པར་མ།༽
  author: བློ་བཟང་རྟ་མགྲིན།
statistics:
  ocr_word_mean_confidence_index: 0.7701858121838606
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1KG15505:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15505
      total_pages: 384
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15505.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7633597562318412
    legacy_id: v002
  I1KG15504:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15504
      total_pages: 266
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15504.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7774163387656386
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
